<a href="https://colab.research.google.com/github/mdaugherity/Numerical2022/blob/main/linear/Week_2_Linear_Systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Systems
PHYS 351, Dr. Daugherity


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Lessons from last time

In [ ]:
x = 2
y = (2**0.5) * (2**0.5)
if x==y:
  print('EQUAL!')
else:
  print('NOT EQUAL?????!?  :(')

NOT EQUAL?????!?  :(


In [ ]:
x = 3.2
y = 2.6 + 0.2 + 0.2 + 0.2
x==y

False

NEVER EVER use == to see if 2 floating point numbers are equal!!!



In [ ]:
if np.abs(x-y)<1e-12:
  print('Close enough!') 

Close enough!


In [ ]:
np.allclose(x,y,

True

Be very, very careful when subtracting 2 "big" numbers and getting a small one


In [ ]:
x = 1.23456789012345
y = 1.23456789012000
x-y  # this answer only has a few sig figs left

3.4501290713251365e-12

# The World's Simplest Math Problems

$y=mx+b$

But to do something more interesting, we could either do harder equations (we'll deal with *non*-linear later) or do lots of equations.

We'll need LINEAR ALGEBRA to do it!

# Linear Algebra 101

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[0],[1]])
C = np.array([[-1,2]])
print(f"A = \n{A}\n")
print(f"B = \n{B}\n")
print(f"C = \n{C}")


A = 
[[1 2]
 [3 4]]

B = 
[[0]
 [1]]

C = 
[[-1  2]]


In [ ]:
A+A

array([[2, 4],
       [6, 8]])

In [ ]:
A+B

array([[1, 2],
       [4, 5]])

WARNING: python will sometimes GUESS and fill in numbers for illegal matrix operations!

In [ ]:
D = np.array([[1,2,3],[4,5,6],[7,8,9]])
A+D

ValueError: ignored

In [ ]:
A*B  # using * makes python NOT do real matrix math

array([[0, 0],
       [3, 4]])

In [ ]:
np.matmul(A,B)  # real matrix mult

array([[2],
       [4]])

In [ ]:
A@B

array([[2],
       [4]])

In [ ]:
B*A

array([[0, 0],
       [3, 4]])

In [ ]:
B@A

ValueError: ignored

In [ ]:
B@C

array([[ 0,  0],
       [-1,  2]])

In [ ]:
C@B

array([[2]])

## Identity, Inverse

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
np.eye(2)  # identity matrix

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.__version__

'1.21.6'

In [ ]:
I = np.identity(2)

In [ ]:
print(A@I)
print(I@A)
print(A)

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
[[1 2]
 [3 4]]


In [ ]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
A@Ainv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
Ainv@A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.allclose(  Ainv@A, I)

True

In [ ]:
A = np.array([[2,1],[-0.5,1]])
A

array([[ 2. ,  1. ],
       [-0.5,  1. ]])

In [ ]:
b = np.array([[6],[1]])
b

array([[6],
       [1]])

In [ ]:
# bad way
Ainv = np.linalg.inv(A)
print(Ainv)
x = Ainv@b
print("\nThe answer is ")
print(x)

[[ 0.4 -0.4]
 [ 0.2  0.8]]

The answer is 
[[2.]
 [2.]]


In [ ]:
# easy, easy
x = np.linalg.solve(A,b)
print("\nThe answer is ")
print(x)


The answer is 
[[2.]
 [2.]]
