<a href="https://colab.research.google.com/github/mdaugherity/Numerical2022/blob/main/intro/Week_1_Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Google Colab
##PHYS 351 - Applied Numerical Methods
##Dr. Daugherity, Abilene Christian University

A quick cheatsheet for doing python in Google Colab


# Text Cells

#This is a title
##This is a subtitle
###This is a subsubtitle

**PHYS 351** - *Fall 2022*

Intro to Google Colab

We can make lists:
* Item 1
* Item 2

We can add links:  [GOOGLE](https://www.google.com)

We can also do MATH:
$x=2, \alpha=x^{2}, \frac{x^3}{b_{1}^{y^3}} $ 





# Basic Python

In [ ]:
x = 42
x = 'apples'
x = [42, 'apples', 'steve']

In [ ]:
x

[42, 'apples', 'steve']

In [ ]:
print(x)

[42, 'apples', 'steve']


# LOGIC
REMEMBER that whitespace **matters**!

In [ ]:
x = -4
if x>0:
  print('positive')
else:
  print('negative')

negative


In [ ]:
x=1
y=1
if x>0 and y>0:
  print('Both positive')

Both positive


# Nice Output
Lots of ways to do this, I like the f-string way

In [ ]:
x = 3.14141241252352
print(f"The answer is {x}")
print(f"The answer is {x:0.3f}")   # padding.dec points
print(f"The answer is {x:0.3e}")   # padding.dec points
print(f"The value is {123864129387641239:,}")  # commas, wow!

The answer is 3.14141241252352
The answer is 3.141
The answer is 3.141e+00
The value is 123,864,129,387,641,239


For more details you can read the documentation:  https://docs.python.org/3/library/string.html#formatspec


# Loops
Confusing thing about loops: LOOPS ONLY WORK ON LISTS OF STUFF

In [ ]:
for i in [0,1,2,3,'steve']:
  print(i)

0
1
2
3
steve


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(3,5):
  print(i)

3
4


In [ ]:
for i in range(0,10,2):
  print(i)

0
2
4
6
8


In [ ]:
x = 0
while x<=5:
  x = x+1
  print(x)

1
2
3
4
5
6


# ARRAYS!

In [ ]:
import numpy as np   # normally put this at the top!

In [ ]:
x = np.array([1,3,5])
print(x)

[1 3 5]


In [ ]:
x = np.array([[1,3,5],[7,9,11]])
print(x)

[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
x = np.zeros(5)   # good for initializing arrays
print(x)

[0. 0. 0. 0. 0.]


In [ ]:
x = np.arange(5)
print(x)
for i in x:
  print(i)

[0 1 2 3 4]
0
1
2
3
4


In [ ]:
# Weird Array Tricks!
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x[0]

0

In [ ]:
x[-1]

9

In [ ]:
x[0:4]

array([0, 1, 2, 3])

In [ ]:
x[0:5:2]

array([0, 2, 4])